import argparse
from pathlib import Path

import torch
from torch.utils.data import DataLoader

from TEST_DATASET import TestDataset
from eeg_pipeline import build_model, choose_device, dataset_paths, resolve_dataset_dir


def parse_args():
    parser = argparse.ArgumentParser(description="Run EEG inference on test set.")
    parser.add_argument("--dataset", default="MDD", help="Dataset name under data-root.")
    parser.add_argument("--data-root", default="course project", help="Root directory containing datasets.")
    parser.add_argument("--checkpoint", required=True, help="Checkpoint generated by train.py")
    parser.add_argument("--batch-size", type=int, default=64)
    parser.add_argument("--num-workers", type=int, default=0)
    parser.add_argument("--device", default="auto")
    parser.add_argument("--output", default=None, help="Prediction output path. Defaults to DATASET_DIR/DATASET.txt")
    return parser.parse_args()


def main():
    args = parse_args()
    device = choose_device(args.device)
    checkpoint = torch.load(args.checkpoint, map_location=device)

    model_args_dict = checkpoint["args"]
    model_args = argparse.Namespace(**model_args_dict)
    model = build_model(
        checkpoint["model_name"],
        checkpoint["channels"],
        checkpoint["num_classes"],
        model_args,
    ).to(device)
    model.load_state_dict(checkpoint["model_state"])
    model.eval()

    dataset_dir = resolve_dataset_dir(args.data_root, args.dataset)
    test_path = dataset_paths(dataset_dir)["test"]
    test_ds = TestDataset(test_path)
    test_loader = DataLoader(
        test_ds,
        batch_size=args.batch_size,
        shuffle=False,
        num_workers=args.num_workers,
    )

    all_preds = []
    with torch.no_grad():
        for data in test_loader:
            data = data.to(device)
            logits = model(data)
            all_preds.extend(logits.argmax(dim=1).cpu().tolist())

    output_path = Path(args.output) if args.output else dataset_dir / f"{args.dataset}.txt"
    with output_path.open("w", encoding="utf-8") as f:
        for pred in all_preds:
            f.write(f"{int(pred)}\n")

    print(f"Predictions: {len(all_preds)}")
    print(f"Output: {output_path}")


if __name__ == "__main__":
    main()
